version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_pro
    ports:
      - "8095:80"
      - "8096:443"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certs/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./docker/certs/privkey.pem:/etc/ssl/private/privkey.pem:ro
 
    depends_on:
      - php

  php:
    build: 
      context: ./php
      dockerfile: Dockerfile
    container_name: php_pro
    volumes:
      - ./:/var/www/html
    user: "www-data"    

  db:
    image: mariadb:latest
    container_name: mariadb_pro
    restart: always
    ports:
      - 3307:3306 
    environment:
      MYSQL_ROOT_PASSWORD: root_produccio
      MYSQL_DATABASE: copypaste_produccio
      MYSQL_USER: producciouser
      MYSQL_PASSWORD: produccio1234
    volumes:
      - db_data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/01-init.sql

  
volumes:
  db_data:
